package org.matsim.plane;

/**
 * This class takes the scenario network as well as the plane-network generated by {@link CreatePlaneSchedule} and fuses it into one network.
 * To make it easier to use, the code automatically removes old flight connections and checks if airports already exist before adding them.
 * Therefore, an already fused network with old data can be also used as scenario network input.
 */
public class AirportNetworkFuser {
	public static void main(String[] args) {
		// TODO
	}
}
