package org.matsim.plane;

import org.matsim.application.MATSimAppCommand;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.network.NetworkUtils;
import org.matsim.core.scenario.MutableScenario;
import org.matsim.core.scenario.ScenarioUtils;
import org.matsim.pt.transitSchedule.api.TransitScheduleReader;
import org.matsim.pt.transitSchedule.api.TransitScheduleWriter;
import org.matsim.vehicles.MatsimVehicleReader;
import org.matsim.vehicles.MatsimVehicleWriter;
import picocli.CommandLine;

/**
 * This class takes the scenario network as well as the plane-network generated by {@link CreatePlaneSchedule} and fuses it into one network.
 * To make it easier to use, the code automatically removes old flight connections and airports.
 * Therefore, an already fused network with old data can be also used as scenario network input.
 */
public class AirportNetworkFuser implements MATSimAppCommand {
	@CommandLine.Option(names = "--network-original-input", description = "Path to original network")
	private String inputOriginalNetwork;

	@CommandLine.Option(names = "--schedule-original-input", description = "Path to original schedule")
	private String inputOriginalSchedule;

	@CommandLine.Option(names = "--vehicle-original-input", description = "Path to original vehicles")
	private String inputOriginalVehicles;

	@CommandLine.Option(names = "--network-plane-input", description = "Path to plane network (generated by CreatePlaneSchedule.java)")
	private String inputPlaneNetwork;

	@CommandLine.Option(names = "--schedule-plane-input", description = "Path to plane schedule (generated by CreatePlaneSchedule.java)")
	private String inputPlaneSchedule;

	@CommandLine.Option(names = "--vehicle-plane-input", description = "Path to plane vehicles (generated by CreatePlaneSchedule.java)")
	private String inputPlaneVehicles;

	@CommandLine.Option(names = "--network-output", description = "Path to output network", required = true)
	private String outputNetwork;

	@CommandLine.Option(names = "--schedule-output", description = "Path to output schedule", required = true)
	private String outputSchedule;

	@CommandLine.Option(names = "--vehicle-output", description = "Path to output vehicles", required = true)
	private String outputVehicles;


	public static void main(String[] args) {
		new AirportNetworkFuser().execute(args);
	}

	@Override
	public Integer call() {
		// Create scenarios (only with necessary elements: network, schedule, vehicles)
		MutableScenario originalScenario = ScenarioUtils.createMutableScenario(ConfigUtils.createConfig());
		originalScenario.setNetwork(NetworkUtils.readNetwork(inputOriginalNetwork));
		(new TransitScheduleReader(originalScenario)).readFile(inputOriginalSchedule);
		(new MatsimVehicleReader(originalScenario.getVehicles())).readFile(inputOriginalVehicles);

		MutableScenario planeScenario = ScenarioUtils.createMutableScenario(ConfigUtils.createConfig());
		planeScenario.setNetwork(NetworkUtils.readNetwork(inputPlaneNetwork));
		(new TransitScheduleReader(planeScenario)).readFile(inputPlaneSchedule);
		(new MatsimVehicleReader(planeScenario.getVehicles())).readFile(inputPlaneVehicles);

		// Remove all old airport nodes
		for(var node : originalScenario.getNetwork().getNodes().values()){
			if(node.getAttributes().getAttribute("airport") != null){
				originalScenario.getNetwork().removeNode(node.getId());
			}
		}

		// Remove all old flight links and airports
		for(var link : originalScenario.getNetwork().getLinks().values()){
			var att = link.getAttributes().getAttribute("flightConnection");
			if ( (att != null && att.equals("yes")) || link.getAttributes().getAttribute("airport") != null){
				originalScenario.getNetwork().removeLink(link.getId());
			}
		}

		// Remove old transit lines
		for(var transitLine : originalScenario.getTransitSchedule().getTransitLines().values()){
			var att = transitLine.getAttributes().getAttribute("flightConnection");
			if(att != null && att.equals("yes")){
				originalScenario.getTransitSchedule().removeTransitLine(transitLine);
			}
		}

		// Remove old vehicles and vehicletypes
		for(var vehicleType : originalScenario.getTransitVehicles().getVehicleTypes().values()){
			var att = vehicleType.getAttributes().getAttribute("airplane");
			if(att != null && att.equals("yes")){
				originalScenario.getTransitVehicles().removeVehicleType(vehicleType.getId());
			}
		}
		for(var vehicle : originalScenario.getTransitVehicles().getVehicles().values()){
			var att = vehicle.getAttributes().getAttribute("airplane");
			if(att != null && att.equals("yes")){
				originalScenario.getTransitVehicles().removeVehicle(vehicle.getId());
			}
		}

		// Add the network, vehicles and schedule into the clened original network
		for(var node : planeScenario.getNetwork().getNodes().values()){
			originalScenario.getNetwork().addNode(node);
		}
		for(var link : planeScenario.getNetwork().getLinks().values()){
			originalScenario.getNetwork().addLink(link);
		}
		for(var transitLine : planeScenario.getTransitSchedule().getTransitLines().values()){
			originalScenario.getTransitSchedule().addTransitLine(transitLine);
		}
		for(var vehicleType : planeScenario.getTransitVehicles().getVehicleTypes().values()){
			originalScenario.getTransitVehicles().addVehicleType(vehicleType);
		}
		for(var vehicle : planeScenario.getTransitVehicles().getVehicles().values()){
			originalScenario.getTransitVehicles().addVehicle(vehicle);
		}

		NetworkUtils.writeNetwork(originalScenario.getNetwork(), outputNetwork);
		new MatsimVehicleWriter(originalScenario.getTransitVehicles()).writeFile(outputVehicles);
		new TransitScheduleWriter(originalScenario.getTransitSchedule()).writeFile(outputSchedule);

		return 0;
	}
}
